birth_year=input("birth_year")
print(type(birth_year))
age=2023-int(birth_year)
print(type(age))
print(age)
weight_lbs=input('weight_lbs')
weight_kg=int(weight_lbs)*0.45
print(weight_kg)
height=input('heigth')
print(' heigth')